# Generated by Django 5.2.8 on 2025-11-13 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_status_name_alter_task_status_alter_task_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_old', to='webapp.type', verbose_name='Тип'),
        ),
    ]
