# Generated by Django 5.2.8 on 2025-11-13 12:22

from django.db import migrations

def transfer_types(apps, schema_editor):
    Task = apps.get_model('webapp.Task')
    for task in Task.objects.all():
        task.types.add(task.type)


def rollback(apps, schema_editor):
    Task = apps.get_model('webapp.Task')
    for task in Task.objects.all():
        task.types.remove(task.type)


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_task_types_alter_task_status_alter_task_type'),
    ]

    operations = [
        migrations.RunPython(transfer_types, reverse_code=rollback),
    ]
