# Generated by Django 5.2.8 on 2025-11-17 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20251113_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='type',
        ),
    ]
